# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\scipipe\scipipe

environment:
  GOPATH: c:\gopath

stack: go 1.12

before_test:
  - set PATH=C:\msys64\mingw64\bin;%PATH%;%GOPATH%\bin
  - go vet ./...

test_script:
  - go test -v -race ./...